Repository I-Oteam/order-management-platform, pull requests merged in 2025-02, with the labels that each got.

#7 Feat/#1 create category
  src/main/java/com/ioteam/order_management_platform/category/controller/CategoryController.java
  src/main/java/com/ioteam/order_management_platform/category/dto/CategoryRequestDto.java
  src/main/java/com/ioteam/order_management_platform/category/dto/CategoryResponseDto.java
  src/main/java/com/ioteam/order_management_platform/category/entity/Category.java
  src/main/java/com/ioteam/order_management_platform/category/execption/CategoryExecption.java
  src/main/java/com/ioteam/order_management_platform/category/repository/CategoryRepository.java
  src/main/java/com/ioteam/order_management_platform/category/service/CategoryService.java
  src/main/java/com/ioteam/order_management_platform/global/entity/BaseEntity.java
  src/test/java/com/ioteam/order_management_platform/category/controller/CategoryControllerTest.java
Labels: feature

#5 feat: review - 리뷰 생성하기 api 추가#3
  src/main/java/com/ioteam/order_management_platform/review/controller/ReviewController.java
  src/main/java/com/ioteam/order_management_platform/review/dto/CreateReviewRequestDto.java
  src/main/java/com/ioteam/order_management_platform/review/dto/ReviewResponseDto.java
  src/main/java/com/ioteam/order_management_platform/review/entity/Review.java
  src/main/java/com/ioteam/order_management_platform/review/repository/ReviewRepository.java
  src/main/java/com/ioteam/order_management_platform/review/service/ReviewService.java
  src/test/java/com/ioteam/order_management_platform/review/controller/ReviewIntegrationTest.java
Labels: feature

#15 Feat/#12 create menu
  src/main/java/com/ioteam/order_management_platform/menu/controller/MenuController.java
  src/main/java/com/ioteam/order_management_platform/menu/dto/CreateMenuRequestDto.java
  src/main/java/com/ioteam/order_management_platform/menu/dto/MenuResponseDto.java
  src/main/java/com/ioteam/order_management_platform/menu/entity/Menu.java
  src/main/java/com/ioteam/order_management_platform/menu/repository/MenuRepository.java
  src/main/java/com/ioteam/order_management_platform/menu/service/MenuService.java
Labels: feature

#11 Feat/#10 modify review
  src/main/java/com/ioteam/order_management_platform/review/controller/ReviewController.java
  src/main/java/com/ioteam/order_management_platform/review/dto/ModifyReviewRequestDto.java
  src/main/java/com/ioteam/order_management_platform/review/entity/Review.java
  src/main/java/com/ioteam/order_management_platform/review/service/ReviewService.java
  src/test/java/com/ioteam/order_management_platform/review/controller/ReviewIntegrationTest.java
Labels: feature

#30 refactor: menu - 메뉴 등록 API 코드 수정
  src/main/java/com/ioteam/order_management_platform/menu/controller/MenuController.java
  src/main/java/com/ioteam/order_management_platform/menu/dto/CreateMenuRequestDto.java
  src/main/java/com/ioteam/order_management_platform/menu/dto/MenuResponseDto.java
  src/main/java/com/ioteam/order_management_platform/menu/entity/Menu.java
  src/main/java/com/ioteam/order_management_platform/menu/service/MenuService.java
Labels: refactoring

#27 Feat/#13 search reviews
  build.gradle
  src/main/java/com/ioteam/order_management_platform/global/config/JpaConfig.java
  src/main/java/com/ioteam/order_management_platform/review/controller/ReviewController.java
  src/main/java/com/ioteam/order_management_platform/review/dto/AdminReviewResponseDto.java
  src/main/java/com/ioteam/order_management_platform/review/dto/CreateReviewRequestDto.java
  src/main/java/com/ioteam/order_management_platform/review/dto/ModifyReviewRequestDto.java
  src/main/java/com/ioteam/order_management_platform/review/dto/ReviewResponseDto.java
  src/main/java/com/ioteam/order_management_platform/review/dto/ReviewSearchCondition.java
  src/main/java/com/ioteam/order_management_platform/review/dto/ReviewUserResponseDto.java
  src/main/java/com/ioteam/order_management_platform/review/entity/Review.java
  src/main/java/com/ioteam/order_management_platform/review/exception/ReviewException.java
  src/main/java/com/ioteam/order_management_platform/review/repository/ReviewRepository.java
  src/main/java/com/ioteam/order_management_platform/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/ioteam/order_management_platform/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/review/service/ReviewService.java
  src/main/java/com/ioteam/order_management_platform/user/entity/User.java
  src/main/resources/application.yml
  src/main/resources/db/data.sql
  src/test/java/com/ioteam/order_management_platform/review/controller/ReviewIntegrationTest.java
Labels: feature

#31 Feat/#20 login user
  src/main/java/com/ioteam/order_management_platform/user/controller/UserController.java
  src/main/java/com/ioteam/order_management_platform/user/exception/UserException.java
  src/main/java/com/ioteam/order_management_platform/user/service/UserService.java
Labels: feature

#35 Feat/#17 get review
  src/main/java/com/ioteam/order_management_platform/global/exception/type/BaseException.java
  src/main/java/com/ioteam/order_management_platform/review/controller/ReviewController.java
  src/main/java/com/ioteam/order_management_platform/review/repository/ReviewRepository.java
  src/main/java/com/ioteam/order_management_platform/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/review/service/ReviewService.java
  src/main/resources/db/data.sql
  src/test/java/com/ioteam/order_management_platform/review/controller/ReviewIntegrationTest.java
  src/test/java/com/ioteam/order_management_platform/utils/security/WithMockCustomUserSecurityContextFactory.java
  src/test/java/com/ioteam/order_management_platform/utils/security/WithMockCustomer.java
Labels: feature

#34 Feat/#21 search category
  src/main/java/com/ioteam/order_management_platform/category/controller/CategoryController.java
  src/main/java/com/ioteam/order_management_platform/category/dto/CategoryRequestDto.java
  src/main/java/com/ioteam/order_management_platform/category/dto/CategoryResponseDto.java
  src/main/java/com/ioteam/order_management_platform/category/dto/CreateCategoryRequestDto.java
  src/main/java/com/ioteam/order_management_platform/category/entity/Category.java
  src/main/java/com/ioteam/order_management_platform/category/execption/CategoryException.java
  src/main/java/com/ioteam/order_management_platform/category/execption/CategoryExecption.java
  src/main/java/com/ioteam/order_management_platform/category/service/CategoryService.java
  src/test/java/com/ioteam/order_management_platform/category/controller/CategoryControllerTest.java
  src/test/java/com/ioteam/order_management_platform/category/controller/CategoryIntegrationTest.java
Labels: refactoring

#38 Feat/#22 refactor review
  src/main/java/com/ioteam/order_management_platform/global/success/SuccessCode.java
  src/main/java/com/ioteam/order_management_platform/review/controller/ReviewController.java
  src/main/java/com/ioteam/order_management_platform/review/dto/CreateReviewRequestDto.java
  src/main/java/com/ioteam/order_management_platform/review/dto/ReviewResponseDto.java
  src/main/java/com/ioteam/order_management_platform/review/entity/Review.java
  src/main/java/com/ioteam/order_management_platform/review/repository/ReviewRepository.java
  src/main/java/com/ioteam/order_management_platform/review/service/ReviewService.java
Labels: feature

#41 refactor: global - 글로벌 설정 추가 수정
  docker-compose-local.yml
  src/main/java/com/ioteam/order_management_platform/user/entity/User.java
  src/main/java/com/ioteam/order_management_platform/user/repository/UserRepository.java
  src/main/java/com/ioteam/order_management_platform/user/security/JwtAuthorizationFilter.java
  src/main/java/com/ioteam/order_management_platform/user/security/UserDetailsImpl.java
  src/main/java/com/ioteam/order_management_platform/user/security/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: refactoring

#42 feat: menu - 메뉴 전체 조회 기능
  src/main/java/com/ioteam/order_management_platform/global/entity/BaseEntity.java
  src/main/java/com/ioteam/order_management_platform/global/success/SuccessCode.java
  src/main/java/com/ioteam/order_management_platform/menu/controller/MenuController.java
  src/main/java/com/ioteam/order_management_platform/menu/dto/req/CreateMenuRequestDto.java
  src/main/java/com/ioteam/order_management_platform/menu/dto/res/MenuListResponseDto.java
  src/main/java/com/ioteam/order_management_platform/menu/dto/res/MenuResponseDto.java
  src/main/java/com/ioteam/order_management_platform/menu/entity/Menu.java
  src/main/java/com/ioteam/order_management_platform/menu/exception/MenuException.java
  src/main/java/com/ioteam/order_management_platform/menu/repository/MenuRepository.java
  src/main/java/com/ioteam/order_management_platform/menu/service/MenuService.java
  src/main/java/com/ioteam/order_management_platform/restaurant/entity/Restaurant.java
  src/main/java/com/ioteam/order_management_platform/restaurant/repository/RestaurantRepository.java
Labels: feature

#44 feat: user - User 전체 조회하기
  src/main/java/com/ioteam/order_management_platform/user/controller/UserController.java
  src/main/java/com/ioteam/order_management_platform/user/dto/AdminUserResponseDto.java
  src/main/java/com/ioteam/order_management_platform/user/dto/UserSearchCondition.java
  src/main/java/com/ioteam/order_management_platform/user/exception/UserException.java
  src/main/java/com/ioteam/order_management_platform/user/repository/UserRepository.java
  src/main/java/com/ioteam/order_management_platform/user/repository/UserRepositoryCustom.java
  src/main/java/com/ioteam/order_management_platform/user/repository/UserRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/user/service/UserService.java
Labels: feature

#45 feat: order - 주문 생성하기
  .gitignore
  src/main/java/com/ioteam/order_management_platform/global/entity/BaseEntity.java
  src/main/java/com/ioteam/order_management_platform/order/controller/OrderController.java
  src/main/java/com/ioteam/order_management_platform/order/dto/CreateOrderRequestDto.java
  src/main/java/com/ioteam/order_management_platform/order/dto/OrderResponseDto.java
  src/main/java/com/ioteam/order_management_platform/order/entity/Order.java
  src/main/java/com/ioteam/order_management_platform/order/enums/OrderStatus.java
  src/main/java/com/ioteam/order_management_platform/order/enums/OrderType.java
  src/main/java/com/ioteam/order_management_platform/order/repository/OrderRepository.java
  src/main/java/com/ioteam/order_management_platform/order/service/OrderService.java
Labels: feature

#47 Feat/#40 read one category
  src/main/java/com/ioteam/order_management_platform/category/controller/CategoryController.java
  src/main/java/com/ioteam/order_management_platform/category/execption/CategoryException.java
  src/main/java/com/ioteam/order_management_platform/category/repository/CategoryRepository.java
  src/main/java/com/ioteam/order_management_platform/category/service/CategoryService.java
  src/main/java/com/ioteam/order_management_platform/global/success/SuccessCode.java
Labels: feature

#50 Feat/#43 create menu
  src/main/java/com/ioteam/order_management_platform/global/dto/CommonResponse.java
  src/main/java/com/ioteam/order_management_platform/global/success/SuccessCode.java
  src/main/java/com/ioteam/order_management_platform/menu/controller/MenuController.java
  src/main/java/com/ioteam/order_management_platform/menu/dto/req/CreateMenuRequestDto.java
  src/main/java/com/ioteam/order_management_platform/menu/service/MenuService.java
Labels: feature

#55 Feat/#32 user api refactoring
  src/main/java/com/ioteam/order_management_platform/user/controller/UserController.java
  src/main/java/com/ioteam/order_management_platform/user/dto/LoginRequestDto.java
  src/main/java/com/ioteam/order_management_platform/user/dto/SignupRequestDto.java
  src/main/java/com/ioteam/order_management_platform/user/security/WebSecurityConfig.java
  src/main/java/com/ioteam/order_management_platform/user/service/UserService.java
Labels: refactoring

#56 feat: menu - 메뉴 상세 조회 API 구현
  src/main/java/com/ioteam/order_management_platform/global/success/SuccessCode.java
  src/main/java/com/ioteam/order_management_platform/menu/controller/MenuController.java
  src/main/java/com/ioteam/order_management_platform/menu/exception/MenuException.java
  src/main/java/com/ioteam/order_management_platform/menu/service/MenuService.java
  src/main/java/com/ioteam/order_management_platform/restaurant/entity/Restaurant.java
  src/main/resources/db/data.sql
Labels: feature

#58 feat: order - 전체 주문 조회 기능 구현
  src/main/java/com/ioteam/order_management_platform/global/entity/BaseEntity.java
  src/main/java/com/ioteam/order_management_platform/global/success/SuccessCode.java
  src/main/java/com/ioteam/order_management_platform/order/controller/OrderController.java
  src/main/java/com/ioteam/order_management_platform/order/dto/OrderListResponseDto.java
  src/main/java/com/ioteam/order_management_platform/order/enums/OrderStatus.java
  src/main/java/com/ioteam/order_management_platform/order/enums/OrderType.java
  src/main/java/com/ioteam/order_management_platform/order/exception/OrderException.java
  src/main/java/com/ioteam/order_management_platform/order/service/OrderService.java
Labels: feature

#62 Feat/#49 search all category
  src/main/java/com/ioteam/order_management_platform/category/controller/CategoryController.java
  src/main/java/com/ioteam/order_management_platform/category/dto/CategoryResponseDto.java
  src/main/java/com/ioteam/order_management_platform/category/dto/CreateCategoryRequestDto.java
  src/main/java/com/ioteam/order_management_platform/category/entity/Category.java
  src/main/java/com/ioteam/order_management_platform/category/repository/CategoryRepository.java
  src/main/java/com/ioteam/order_management_platform/category/service/CategoryService.java
Labels: feature, fix

#59 Feat/#51 search by user
  build.gradle
  src/main/java/com/ioteam/order_management_platform/review/controller/ReviewController.java
  src/main/java/com/ioteam/order_management_platform/review/dto/ModifyReviewRequestDto.java
  src/main/java/com/ioteam/order_management_platform/review/dto/ReviewSearchCondition.java
  src/main/java/com/ioteam/order_management_platform/review/dto/req/AdminReviewSearchCondition.java
  src/main/java/com/ioteam/order_management_platform/review/dto/req/CreateReviewRequestDto.java
  src/main/java/com/ioteam/order_management_platform/review/dto/req/ModifyReviewRequestDto.java
  src/main/java/com/ioteam/order_management_platform/review/dto/res/AdminReviewResponseDto.java
  src/main/java/com/ioteam/order_management_platform/review/dto/res/ReviewResponseDto.java
  src/main/java/com/ioteam/order_management_platform/review/dto/res/ReviewRestaurantResponseDto.java
  src/main/java/com/ioteam/order_management_platform/review/dto/res/ReviewUserResponseDto.java
  src/main/java/com/ioteam/order_management_platform/review/entity/Review.java
  src/main/java/com/ioteam/order_management_platform/review/exception/ReviewException.java
  src/main/java/com/ioteam/order_management_platform/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/ioteam/order_management_platform/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/review/service/ReviewService.java
  src/main/resources/db/data.sql
  src/test/java/com/ioteam/order_management_platform/review/controller/ReviewIntegrationTest.java
Labels: feature

#64 Feat/#52 search by res
  src/main/java/com/ioteam/order_management_platform/restaurant/entity/Restaurant.java
  src/main/java/com/ioteam/order_management_platform/review/controller/ReviewController.java
  src/main/java/com/ioteam/order_management_platform/review/dto/req/CreateReviewRequestDto.java
  src/main/java/com/ioteam/order_management_platform/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/ioteam/order_management_platform/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/review/service/ReviewService.java
  src/main/resources/db/data.sql
  src/test/java/com/ioteam/order_management_platform/review/controller/ReviewIntegrationTest.java
Labels: feature

#65 feat/#63 order - 주문 상세 정보 조회 기능 구현
  src/main/java/com/ioteam/order_management_platform/global/success/SuccessCode.java
  src/main/java/com/ioteam/order_management_platform/order/controller/OrderController.java
  src/main/java/com/ioteam/order_management_platform/order/dto/req/CreateOrderRequestDto.java
  src/main/java/com/ioteam/order_management_platform/order/dto/res/OrderListResponseDto.java
  src/main/java/com/ioteam/order_management_platform/order/dto/res/OrderResponseDto.java
  src/main/java/com/ioteam/order_management_platform/order/service/OrderService.java
Labels: feature

#71 Feat/#68 update category
  src/main/java/com/ioteam/order_management_platform/category/controller/CategoryController.java
  src/main/java/com/ioteam/order_management_platform/category/dto/req/CreateCategoryRequestDto.java
  src/main/java/com/ioteam/order_management_platform/category/dto/req/UpdateCategoryRequestDto.java
  src/main/java/com/ioteam/order_management_platform/category/dto/res/CategoryResponseDto.java
  src/main/java/com/ioteam/order_management_platform/category/entity/Category.java
  src/main/java/com/ioteam/order_management_platform/category/service/CategoryService.java
  src/main/java/com/ioteam/order_management_platform/global/jpa/UserAuditorAware.java
  src/main/java/com/ioteam/order_management_platform/global/success/SuccessCode.java
  src/test/java/com/ioteam/order_management_platform/category/controller/CategoryIntegrationTest.java
Labels: bug, feature

#72 feat: menu - 메뉴 수정 API 구현 #57
  src/main/java/com/ioteam/order_management_platform/global/success/SuccessCode.java
  src/main/java/com/ioteam/order_management_platform/menu/controller/MenuController.java
  src/main/java/com/ioteam/order_management_platform/menu/dto/req/UpdateMenuRequestDto.java
  src/main/java/com/ioteam/order_management_platform/menu/entity/Menu.java
  src/main/java/com/ioteam/order_management_platform/menu/service/MenuService.java
  src/main/resources/db/data.sql
Labels: feature

#73 feat: RestaurantScore 스케쥴링 - 1차 구현
  src/main/java/com/ioteam/order_management_platform/OrderManagementPlatformApplication.java
  src/main/java/com/ioteam/order_management_platform/restaurant/entity/RestaurantScore.java
  src/main/java/com/ioteam/order_management_platform/restaurant/repository/RestaurantScoreRepository.java
  src/main/java/com/ioteam/order_management_platform/restaurant/scheduling/RestaurantScoreScheduler.java
Labels: feature

#76 feat: RestaurantScore - 수정
  src/main/java/com/ioteam/order_management_platform/restaurant/repository/RestaurantScoreRepository.java
  src/main/java/com/ioteam/order_management_platform/restaurant/scheduling/RestaurantScoreScheduler.java
  src/main/resources/db/data.sql
Labels: feature

#77 feat: Category - 카테고리 소프트삭제 API 구현 #74
  src/main/java/com/ioteam/order_management_platform/category/controller/CategoryController.java
  src/main/java/com/ioteam/order_management_platform/category/repository/CategoryRepository.java
  src/main/java/com/ioteam/order_management_platform/category/service/CategoryService.java
Labels: feature

#79 Feat/#61 user refactor
  src/main/java/com/ioteam/order_management_platform/global/success/SuccessCode.java
  src/main/java/com/ioteam/order_management_platform/user/controller/UserController.java
  src/main/java/com/ioteam/order_management_platform/user/dto/req/LoginRequestDto.java
  src/main/java/com/ioteam/order_management_platform/user/dto/req/SignupRequestDto.java
  src/main/java/com/ioteam/order_management_platform/user/dto/req/UserSearchCondition.java
  src/main/java/com/ioteam/order_management_platform/user/dto/res/AdminUserResponseDto.java
  src/main/java/com/ioteam/order_management_platform/user/dto/res/UserInfoResponseDto.java
  src/main/java/com/ioteam/order_management_platform/user/exception/UserException.java
  src/main/java/com/ioteam/order_management_platform/user/repository/UserRepository.java
  src/main/java/com/ioteam/order_management_platform/user/repository/UserRepositoryCustom.java
  src/main/java/com/ioteam/order_management_platform/user/repository/UserRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/user/security/JwtAuthenticationFilter.java
  src/main/java/com/ioteam/order_management_platform/user/security/TokenConfig.java
  src/main/java/com/ioteam/order_management_platform/user/service/UserService.java
  src/main/resources/properties/key.yml
Labels: feature, fix, refactoring

#83 docs: infra - yml 파일 내용 수정
  src/main/resources/application.yml
  src/main/resources/properties/datasource.yml
  src/main/resources/properties/jpa.yml
  src/main/resources/properties/key.yml
Labels: feature

#86 Feat/#60 payments create
  src/main/java/com/ioteam/order_management_platform/global/success/SuccessCode.java
  src/main/java/com/ioteam/order_management_platform/payment/controller/PaymentController.java
  src/main/java/com/ioteam/order_management_platform/payment/dto/req/CreatePaymentRequestDto.java
  src/main/java/com/ioteam/order_management_platform/payment/dto/res/PaymentResponseDto.java
  src/main/java/com/ioteam/order_management_platform/payment/entity/Payment.java
  src/main/java/com/ioteam/order_management_platform/payment/exception/PaymentException.java
  src/main/java/com/ioteam/order_management_platform/payment/repository/PaymentRepository.java
  src/main/java/com/ioteam/order_management_platform/payment/service/PaymentService.java
Labels: feature

#88 fix: menu - 메뉴 수정 API 검증 로직 추가 #78
  src/main/java/com/ioteam/order_management_platform/menu/controller/MenuController.java
  src/main/java/com/ioteam/order_management_platform/menu/exception/MenuException.java
  src/main/java/com/ioteam/order_management_platform/menu/repository/MenuRepository.java
  src/main/java/com/ioteam/order_management_platform/menu/service/MenuService.java
  src/main/resources/db/data.sql
Labels: feature

#93 feat: menu - 메뉴 조회 시 권한과 가게 주인 여부에 따른 조회 조건 추가 #75
  src/main/java/com/ioteam/order_management_platform/menu/controller/MenuController.java
  src/main/java/com/ioteam/order_management_platform/menu/repository/MenuCustomRepository.java
  src/main/java/com/ioteam/order_management_platform/menu/repository/MenuCustomRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/menu/repository/MenuRepository.java
  src/main/java/com/ioteam/order_management_platform/menu/service/MenuService.java
  src/main/resources/db/data.sql
Labels: feature

#96 feat: menu - 단건 메뉴 숨김 처리 api 구현 #95
  src/main/java/com/ioteam/order_management_platform/menu/controller/MenuController.java
  src/main/java/com/ioteam/order_management_platform/menu/entity/Menu.java
  src/main/java/com/ioteam/order_management_platform/menu/service/MenuService.java
Labels: feature

#101 feat : payment - 결제 삭제#85
  src/main/java/com/ioteam/order_management_platform/global/success/SuccessCode.java
  src/main/java/com/ioteam/order_management_platform/payment/controller/PaymentController.java
  src/main/java/com/ioteam/order_management_platform/payment/service/PaymentService.java
Labels: feature

#107 Refactor #103 menu 조회 조건 추가
  src/main/java/com/ioteam/order_management_platform/menu/repository/MenuCustomRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/menu/repository/MenuRepository.java
  src/main/java/com/ioteam/order_management_platform/menu/service/MenuService.java
  src/main/java/com/ioteam/order_management_platform/restaurant/repository/RestaurantRepository.java
Labels: refactoring

#108 Feat/#69 refactor review
  src/main/java/com/ioteam/order_management_platform/global/jpa/UserAuditorAware.java
  src/main/java/com/ioteam/order_management_platform/order/repository/OrderRepository.java
  src/main/java/com/ioteam/order_management_platform/review/controller/ReviewController.java
  src/main/java/com/ioteam/order_management_platform/review/dto/req/CreateReviewRequestDto.java
  src/main/java/com/ioteam/order_management_platform/review/dto/req/ModifyReviewRequestDto.java
  src/main/java/com/ioteam/order_management_platform/review/exception/ReviewException.java
  src/main/java/com/ioteam/order_management_platform/review/repository/ReviewRepository.java
  src/main/java/com/ioteam/order_management_platform/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/review/service/ReviewService.java
  src/main/resources/db/data.sql
  src/test/java/com/ioteam/order_management_platform/review/controller/ReviewIntegrationTest.java
Labels: refactoring

#110 Feat/#105 search one restaurant
  src/main/java/com/ioteam/order_management_platform/restaurant/controller/RestaurantController.java
  src/main/java/com/ioteam/order_management_platform/restaurant/execption/RestaurantException.java
  src/main/java/com/ioteam/order_management_platform/restaurant/service/RestaurantService.java
  src/main/resources/db/data.sql
Labels: feature

#118 Feat: order - 삭제 기능 구현
  src/main/java/com/ioteam/order_management_platform/order/controller/OrderController.java
  src/main/java/com/ioteam/order_management_platform/order/entity/Order.java
  src/main/java/com/ioteam/order_management_platform/order/exception/OrderException.java
  src/main/java/com/ioteam/order_management_platform/order/repository/OrderRepository.java
  src/main/java/com/ioteam/order_management_platform/order/service/OrderService.java
Labels: feature

#121 Feat/#115 refactoring user
  src/main/java/com/ioteam/order_management_platform/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ioteam/order_management_platform/global/exception/type/BaseException.java
  src/main/java/com/ioteam/order_management_platform/user/controller/UserController.java
  src/main/java/com/ioteam/order_management_platform/user/dto/req/SignupRequestDto.java
  src/main/java/com/ioteam/order_management_platform/user/dto/res/LoginResponseDto.java
  src/main/java/com/ioteam/order_management_platform/user/dto/res/UserInfoResponseDto.java
  src/main/java/com/ioteam/order_management_platform/user/exception/UserException.java
  src/main/java/com/ioteam/order_management_platform/user/repository/UserRepository.java
  src/main/java/com/ioteam/order_management_platform/user/service/UserService.java
Labels: refactoring

#122 Feat/#114 update restaurant
  src/main/java/com/ioteam/order_management_platform/restaurant/controller/RestaurantController.java
  src/main/java/com/ioteam/order_management_platform/restaurant/dto/req/ModifyRestaurantRequestDto.java
  src/main/java/com/ioteam/order_management_platform/restaurant/dto/res/RestaurantResponseDto.java
  src/main/java/com/ioteam/order_management_platform/restaurant/entity/Restaurant.java
  src/main/java/com/ioteam/order_management_platform/restaurant/execption/RestaurantException.java
  src/main/java/com/ioteam/order_management_platform/restaurant/service/RestaurantService.java
Labels: feature

#125 Feat/#120 search order by res
  src/main/java/com/ioteam/order_management_platform/global/success/SuccessCode.java
  src/main/java/com/ioteam/order_management_platform/order/controller/OrderController.java
  src/main/java/com/ioteam/order_management_platform/order/dto/req/OrderByRestaurantSearchCondition.java
  src/main/java/com/ioteam/order_management_platform/order/exception/OrderException.java
  src/main/java/com/ioteam/order_management_platform/order/repository/OrderRepository.java
  src/main/java/com/ioteam/order_management_platform/order/repository/OrderRepositoryCustom.java
  src/main/java/com/ioteam/order_management_platform/order/repository/OrderRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/order/service/OrderService.java
  src/main/java/com/ioteam/order_management_platform/restaurant/repository/RestaurantRepository.java
  src/main/resources/db/data.sql
  src/test/java/com/ioteam/order_management_platform/order/controller/OrderControllerTest.java
  src/test/java/com/ioteam/order_management_platform/review/controller/ReviewIntegrationTest.java
Labels: feature

#126 refactor : 결제 - 생성 서비스 리팩토링#123
  src/main/java/com/ioteam/order_management_platform/order/repository/OrderRepository.java
  src/main/java/com/ioteam/order_management_platform/payment/exception/PaymentException.java
  src/main/java/com/ioteam/order_management_platform/payment/service/PaymentService.java
Labels: refactoring

#127 feat : 결제 - 상태 변경 api #102
  src/main/java/com/ioteam/order_management_platform/global/success/SuccessCode.java
  src/main/java/com/ioteam/order_management_platform/payment/controller/PaymentController.java
  src/main/java/com/ioteam/order_management_platform/payment/entity/Payment.java
  src/main/java/com/ioteam/order_management_platform/payment/entity/PaymentStatusEnum.java
  src/main/java/com/ioteam/order_management_platform/payment/exception/PaymentException.java
  src/main/java/com/ioteam/order_management_platform/payment/service/PaymentService.java
Labels: feature

#130 Feat/#119 refactor order
  src/main/java/com/ioteam/order_management_platform/order/controller/OrderController.java
  src/main/java/com/ioteam/order_management_platform/order/entity/Order.java
  src/main/java/com/ioteam/order_management_platform/order/exception/OrderException.java
  src/main/java/com/ioteam/order_management_platform/order/repository/OrderRepository.java
  src/main/java/com/ioteam/order_management_platform/order/service/OrderService.java
Labels: refactoring

#131 Feat/#124 search all restaurant
  src/main/java/com/ioteam/order_management_platform/restaurant/controller/RestaurantController.java
  src/main/java/com/ioteam/order_management_platform/restaurant/dto/res/RestaurantResponseDto.java
  src/main/java/com/ioteam/order_management_platform/restaurant/repository/RestaurantRepository.java
  src/main/java/com/ioteam/order_management_platform/restaurant/service/RestaurantService.java
  src/main/resources/db/data.sql
Labels: feature

#134 fix: Data.sql - 더미데이터 필드 수정 #133
  src/main/resources/db/data.sql
Labels: bug, fix

#137 Feat/#132 user payment refactoring
  src/main/java/com/ioteam/order_management_platform/payment/controller/PaymentController.java
  src/main/java/com/ioteam/order_management_platform/payment/entity/Payment.java
  src/main/java/com/ioteam/order_management_platform/payment/repository/PaymentRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/payment/service/PaymentService.java
  src/main/java/com/ioteam/order_management_platform/user/controller/UserController.java
  src/main/java/com/ioteam/order_management_platform/user/repository/UserRepositoryImpl.java
Labels: refactoring

#141 feat: 리뷰 - 리뷰 리팩토링 #140
  src/main/java/com/ioteam/order_management_platform/global/exception/type/BaseException.java
  src/main/java/com/ioteam/order_management_platform/review/controller/ReviewController.java
  src/main/java/com/ioteam/order_management_platform/review/dto/res/AdminReviewResponseDto.java
  src/main/java/com/ioteam/order_management_platform/review/dto/res/ReviewResponseDto.java
  src/main/java/com/ioteam/order_management_platform/review/dto/res/ReviewRestaurantResponseDto.java
  src/main/java/com/ioteam/order_management_platform/review/dto/res/ReviewUserResponseDto.java
  src/main/java/com/ioteam/order_management_platform/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/review/service/ReviewService.java
Labels: refactoring

#144 Feat/#143 refactor global
  .github/workflows/aws-deploy.yml
  .github/workflows/docker-build.yml
  src/main/java/com/ioteam/order_management_platform/global/dto/CommonErrorResponse.java
  src/main/java/com/ioteam/order_management_platform/global/exception/GlobalExceptionHandler.java
Labels: refactoring

#145 feat: 주문 - 주문 리팩토링 #142
  src/main/java/com/ioteam/order_management_platform/order/controller/OrderController.java
  src/main/java/com/ioteam/order_management_platform/order/repository/OrderRepository.java
  src/main/java/com/ioteam/order_management_platform/order/repository/OrderRepositoryImpl.java
Labels: refactoring

#146 feat: 상품 조회 시 정렬 기능 추가 #139
  .gitignore
  src/main/java/com/ioteam/order_management_platform/menu/controller/MenuController.java
  src/main/java/com/ioteam/order_management_platform/menu/repository/MenuCustomRepository.java
  src/main/java/com/ioteam/order_management_platform/menu/repository/MenuCustomRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/menu/service/MenuService.java
Labels: feature

#147 feat: 요구사항에 따른 상품 상태 추가
  src/main/java/com/ioteam/order_management_platform/menu/controller/MenuController.java
  src/main/java/com/ioteam/order_management_platform/menu/dto/req/CreateMenuRequestDto.java
  src/main/java/com/ioteam/order_management_platform/menu/dto/req/UpdateMenuRequestDto.java
  src/main/java/com/ioteam/order_management_platform/menu/dto/res/MenuResponseDto.java
  src/main/java/com/ioteam/order_management_platform/menu/entity/Menu.java
  src/main/java/com/ioteam/order_management_platform/menu/entity/MenuStatus.java
  src/main/java/com/ioteam/order_management_platform/menu/repository/MenuCustomRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/menu/service/MenuService.java
Labels: feature

#151 Feat/#135 search score restaurant
  src/main/java/com/ioteam/order_management_platform/restaurant/controller/RestaurantController.java
  src/main/java/com/ioteam/order_management_platform/restaurant/dto/res/RestaurantResponseDto.java
  src/main/java/com/ioteam/order_management_platform/restaurant/entity/Restaurant.java
  src/main/java/com/ioteam/order_management_platform/restaurant/entity/RestaurantScore.java
  src/main/java/com/ioteam/order_management_platform/restaurant/execption/RestaurantScoreException.java
  src/main/java/com/ioteam/order_management_platform/restaurant/repository/RestaurantRepository.java
  src/main/java/com/ioteam/order_management_platform/restaurant/repository/RestaurantScoreRepository.java
  src/main/java/com/ioteam/order_management_platform/restaurant/service/RestaurantService.java
  src/main/resources/db/data.sql
Labels: feature

#152 Refactor/#150 refactor http client
  build.gradle
  src/main/java/com/ioteam/order_management_platform/ai/service/AiService.java
  src/main/java/com/ioteam/order_management_platform/global/config/RestClientConfig.java
  src/main/java/com/ioteam/order_management_platform/menu/exception/MenuException.java
Labels: feature

#154 Feat/#153 refactor review
  src/main/java/com/ioteam/order_management_platform/review/dto/req/CreateReviewRequestDto.java
  src/main/java/com/ioteam/order_management_platform/review/dto/res/ReviewResponseDto.java
  src/main/java/com/ioteam/order_management_platform/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/review/service/ReviewService.java
  src/main/resources/db/data.sql
Labels: refactoring

#156 feat: Restaurant - 가게 카테고리 별 조회 API #155
  src/main/java/com/ioteam/order_management_platform/restaurant/controller/RestaurantController.java
  src/main/java/com/ioteam/order_management_platform/restaurant/repository/RestaurantRepository.java
  src/main/java/com/ioteam/order_management_platform/restaurant/service/RestaurantService.java
Labels: feature

#161 refactor: 권한 확인 로직 수정 #159
  src/main/java/com/ioteam/order_management_platform/ai/service/AiService.java
  src/main/java/com/ioteam/order_management_platform/menu/controller/MenuController.java
  src/main/java/com/ioteam/order_management_platform/menu/service/MenuService.java
Labels: feature

#164 feat: Pageable 페이지 사이즈 제한 기능 추가 #160
  src/main/java/com/ioteam/order_management_platform/global/config/CustomPageableArgumentResolver.java
  src/main/java/com/ioteam/order_management_platform/global/config/WebConfig.java
Labels: feature

#167 Refactor/#165 refactor global infra
  .github/workflows/aws-deploy.yml
  .github/workflows/docker-build.yml
  nginx/conf.d/default.conf
  src/main/java/com/ioteam/order_management_platform/OrderManagementPlatformApplication.java
  src/main/java/com/ioteam/order_management_platform/global/TestController.java
  src/main/java/com/ioteam/order_management_platform/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ioteam/order_management_platform/restaurant/scheduling/RestaurantScoreScheduler.java
  src/main/resources/application.yml
  src/main/resources/error-file-appender.xml
  src/main/resources/info-file-appender.xml
  src/main/resources/logback-spring.xml
  src/main/resources/properties/jpa.yml
Labels: refactoring

#171 Refactor/#170 refactor global
  src/main/java/com/ioteam/order_management_platform/global/exception/type/BaseException.java
  src/main/java/com/ioteam/order_management_platform/global/utils/QuerydslUtil.java
  src/main/java/com/ioteam/order_management_platform/order/dto/req/AdminOrderSearchCondition.java
  src/main/java/com/ioteam/order_management_platform/order/repository/OrderRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/user/jwt/JwtUtil.java
  src/main/java/com/ioteam/order_management_platform/user/security/JwtAccessDeniedHandler.java
  src/main/java/com/ioteam/order_management_platform/user/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/ioteam/order_management_platform/user/security/WebSecurityConfig.java
Labels: refactoring

#166 Refactor/#159 메뉴 리팩토링
  src/main/java/com/ioteam/order_management_platform/ai/controller/AiController.java
  src/main/java/com/ioteam/order_management_platform/ai/service/AiService.java
  src/main/java/com/ioteam/order_management_platform/menu/repository/MenuCustomRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/menu/service/MenuService.java
  src/main/java/com/ioteam/order_management_platform/restaurant/entity/Restaurant.java
Labels: feature

#177 Feat/#160 sort global pazing
  src/main/java/com/ioteam/order_management_platform/order/repository/OrderRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/review/repository/ReviewRepositoryImpl.java
  src/main/resources/db/data.sql
Labels: feature

#184 refactor: Restaurant - Prepersist리펙토링 #183
  src/main/java/com/ioteam/order_management_platform/restaurant/controller/RestaurantController.java
  src/main/java/com/ioteam/order_management_platform/restaurant/entity/Restaurant.java
  src/main/java/com/ioteam/order_management_platform/restaurant/entity/RestaurantScore.java
Labels: feature

#186 refactor: Restaurant - Prepersist리펙토링 #183
  src/main/java/com/ioteam/order_management_platform/restaurant/entity/RestaurantScore.java
Labels: refactoring

#189 docs: global - 로깅 리팩토링 #188
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/main/resources/logback/error-file-appender.xml
  src/main/resources/logback/info-file-appender.xml
Labels: refactoring

#187 Test/#174 menu test
  src/main/java/com/ioteam/order_management_platform/menu/dto/req/UpdateMenuRequestDto.java
  src/main/resources/db/data.sql
  src/test/java/com/ioteam/order_management_platform/menu/controller/MenuIntegrationTest.java
Labels: test

#193 feat: review - 리뷰 실패 테스트 코드 추가 #192
  src/main/java/com/ioteam/order_management_platform/review/exception/ReviewException.java
  src/main/resources/db/data.sql
  src/test/java/com/ioteam/order_management_platform/review/controller/ReviewIntegrationTest.java
Labels: feature

#197 refactor: global - 로깅 리팩토링 #188
  src/main/java/com/ioteam/order_management_platform/global/filter/LoggingFilter.java
Labels: refactoring

#195 refactor : 인프라 - dockerfile 수정#194
  Dockerfile
Labels: refactoring

#198 Refactor/#196 refactor review
  src/main/java/com/ioteam/order_management_platform/order/entity/Order.java
  src/main/java/com/ioteam/order_management_platform/order/enums/OrderStatus.java
  src/main/java/com/ioteam/order_management_platform/review/dto/req/CreateReviewRequestDto.java
  src/main/java/com/ioteam/order_management_platform/review/entity/Review.java
  src/main/java/com/ioteam/order_management_platform/review/exception/ReviewException.java
  src/main/java/com/ioteam/order_management_platform/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/ioteam/order_management_platform/review/service/ReviewService.java
  src/main/java/com/ioteam/order_management_platform/user/entity/UserRoleEnum.java
Labels: refactoring

#199 Refactor/#179 payment get payment refactoring
  src/main/java/com/ioteam/order_management_platform/payment/entity/Payment.java
  src/main/java/com/ioteam/order_management_platform/payment/service/PaymentService.java
  src/main/java/com/ioteam/order_management_platform/payment/service/strategy/PaymentRetrieveStrategies.java
  src/main/java/com/ioteam/order_management_platform/payment/service/strategy/PaymentRetrieveStrategy.java
  src/main/java/com/ioteam/order_management_platform/payment/service/strategy/role/AdminPaymentRetrieveStrategy.java
  src/main/java/com/ioteam/order_management_platform/payment/service/strategy/role/CustomerPaymentRetrieveStrategy.java
  src/main/java/com/ioteam/order_management_platform/payment/service/strategy/role/OwnerPaymentRetrieveStrategy.java
Labels: refactoring

#202 Refactor/#201 refactor global
  build.gradle
  deploy.sh
  src/main/java/com/ioteam/order_management_platform/global/utils/QuerydslUtil.java
  src/test/java/com/ioteam/order_management_platform/global/BaseTest.java
  src/test/java/com/ioteam/order_management_platform/global/IntegrationBaseTest.java
  src/test/java/com/ioteam/order_management_platform/utils/DatabaseCleanUp.java
Labels: refactoring
